# cmake/toolchains/sdcc-stm8.cmake
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR stm8)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER   sdcc)
set(CMAKE_ASM_COMPILER sdcc)
set(CMAKE_OBJCOPY      sdobjcopy CACHE FILEPATH "")
set(CMAKE_SIZE         sdsize CACHE FILEPATH "")

set(CMAKE_OSX_ARCHITECTURES "" CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "" FORCE)
set(CMAKE_OSX_SYSROOT "" CACHE PATH "" FORCE)
